### PR TITLE
nxt_filer improvements

### PR DESCRIPTION
**Pull request by dlech**
This makes nxt_filer look a bit more like a modern GTK application. No functional changes.

### CODE REVIEW

**Comment by dlech** [comment]
### Before

selection_020

selection_015


### After

selection_016

selection_017

selection_018

selection_019

**Comment by dlech** [comment]
Key points:

* About dialog is now on application menu instead of button
* Use built-in GTK About dialog
* Add status bar to show status instead of putting it on the connect button
* Use built-in command line option handling

Tested on Linux and macOS.

**Comment by GolddolphinSKB-Fexcraftian** [comment]
Good work, except I'm not sure about adding your name for the copyright, I'll wait until @Eelviny looks at it.

**Comment by dlech** [comment]
I thought nxt-python was pretty much python3 only now, so I didn't test this on python2.

**Comment by dlech** [comment]
> In addition, on macOS, I don't see the Gtk Application Menu?

This is the application menu that is present for all Mac applications. It was working when I tested this code.

**Comment by tcwan** [comment]
nxtfilemgr

This is the screen I get. The menubar belongs to XQuartz, it doesn't have any entries such as "About" for nxtfilemgr.

**Comment by dlech** [comment]
As indicated by the shebang, this program is intended to run with python3. Given the fact that python2 is end of life in 18 months, I don't think it is worth the effort to try to make it work with python2.

I'm using homebrew to get python3 and gtk3. I'm guessing the MacPorts version of GTK must use the X backend instead of the native Cocoa backend for some reason. So, without some kind of window manager running in XQuartz, I guess you won't see a menu. This will be a problem with other GTK applications as well.

**Comment by tcwan** [comment]
@dlech:
Ok, noted on the python2 porting issue.

I have other Gtk+ programs, e.g. dia which show its application menu correctly.
So there must be an API call that is needed to display it.
dia

**Comment by dlech** [comment]
This is what I mean when I say "application menu":

selection_014

I realize the same term is used for what you have shown as well. However, modern gnome applications use the type of menu I have shown.

I suppose we could add some code that adds some other way of accessing the about dialog for you when the system does not support this sort of menu. I don't really have a way to reproduce the problem though since I get the menu on my Mac.

**Comment by dlech** [comment]
Also, I think you can install gnome from macports and maybe get this menu to show up somewhere.

**Comment by dlech** [comment]
Basically, we could add an `else:` here: https://github.com/Eelviny/nxt-python/pull/146/files#diff-5c7fcd0fd4a658ffc21d90d06fa57f20R464 that adds an old-style menu or toolbar when the app menu is not show.

**Comment by tcwan** [comment]
@dlech:

I don't install gnome since it is quite a large binary.
In any case, I'm not familiar with python3, so I'll leave it to you to update it for the nxt-python repository.

I'll maintain a non-menubar version of `nxtfilemgr` for python 2 in the meantime in my own project repository.

**Comment by Eelviny** [comment]
@GolddolphinSKB-Fexcraftian I checked it, and I'm fine with the "created by" message, as it does not imply copyright to any particular person.

What's the status on this at the moment? Any more work that needs to be done to it, or is this ready to merge?

**Comment by Eelviny** [comment]
Also, the new version is exclusively targeting Python 3.0, so 2.0 is a second class citizen here. That being said, I'll be willing to merge something into the 2.0 branch in a different PR, but no releases will be made.

**Comment by dlech** [comment]
> What's the status on this at the moment? Any more work that needs to be done to it, or is this ready to merge?

I just rebased and tested this again a couple weeks ago, so as far as I am concerned, it is ready to merge.

**Comment by tcwan** [comment]
@Eelviny:
The patches [I submitted](https://github.com/Eelviny/nxt-python/pull/152) were to fix issues with python 2.7 support. Feel free to merge it into the 2.7 branch if you like.

**Pull request merged**
