### PR TITLE
Changed to solve this issue: https://github.com/Eelviny/nxt-python/is…

### PR DESCRIPTION
**Pull request by hermlon**
…sues/124
I'm unsure why @GolddolphinSKB-Fexcraftian didn't fix this when he himself said converting it to string worked. (So does it for me, I'm not into this project so if I'm missing something please correct me!)

### CODE REVIEW

**Comment by GolddolphinSKB-Fexcraftian** [comment]
Which python version are you using? Using a string at all seems unnecessary for byte manipulation. The `bytes` type is a python3 thing, python2 may have issues with it.
By now python3 should work flawlessly as far as I have tested, so I would advise using that for the meanwhile.

**Comment by hermlon** [comment]
Python 3. I got exactly the linked error when running the nxt_test script and it was gone after adding the str(). Any ideas why it works for you but not for me?

**Comment by GolddolphinSKB-Fexcraftian** [comment]
Just to check, you're running from the main branch, not a release? I'll do some more testing to see if I can work out what's happening.

**Comment by hermlon** [comment]
Ok, I don't know what happened to me before. I downloaded the master branch again and everything just works fine...

**Comment by GolddolphinSKB-Fexcraftian** [comment]
Okay, I guess you just had an earlier version. Thanks for the input though ;)

**Pull request closed without merging**
