### PR TITLE
Implement ideas from #72

### PR DESCRIPTION
**Pull request by Eelviny**
Implemented the changes from this. If there's anything out of order, please say so. I'll hit merge once everything is in order.

### CODE REVIEW

**Comment by guihi** [comment]
The changes made are working fine for analog sensors.
However, we need further changes concerning bytes to make the **ultrasonic** work, because its a digital sensor with other communication including strings. Because we are using BytesIO in Python3, we have to convert bytes in string and vice versa giving the encoding. I assume windows-1252, because its the most common for characters above 0xf0. utf-8 won't work for the code 0xff.

I have tested Ultrasonic with the following changes in addition.
**in telegram.py**
from line 58 (Thus, it is to be consistent. I don't know if it's used any more.):
```python
    def __str__(self):
        return self.pkt.getvalue().decode('windows-1252')
```
from line 68 (important!):
```python
    def add_string(self, n_bytes, v):
        self.pkt.write(pack('%ds' % n_bytes, v.encode('windows-1252')))
```
**in sensor/digital.py**
from line 154:
```python
    def get_sensor_info(self):
        version = self.read_value('version')[0].decode('windows-1252').split('\0')[0]
        product_id = self.read_value('product_id')[0].decode('windows-1252').split('\0')[0] [0]
        sensor_type = self.read_value('sensor_type')[0].decode('windows-1252').split('\0')[0]
        return SensorInfo(version, product_id, sensor_type)
```

**Comment by Eelviny** [comment]
Any other fixes needed on this subject?
A few people have said they will test, so hopefully we can get this merged soon.

**Comment by guihi** [comment]
One more fix of the same type is necessary in generic.py at line 105:
```python
    def get_measurement_units(self):
        return self.read_value('measurement_units')[0].decode('windows-1252').split('\0')[0]
```
Them all of my sensors are working fine (sound, light, touch, ultrasonic).
Till now I have not tested Bluetooth, only USB.

**Comment by Eelviny** [comment]
Alright, I deem this ready for merging.

**Pull request merged**
