### PR TITLE
nxt_filer: fix error:

### PR DESCRIPTION
**Pull request by feinstaub**
File "./nxt_filer", line 47
print('Pushing %s (%d bytes) ...' % (fname, w.size), end=' ')
                                                            ^
And use modern string formatting.

### CODE REVIEW

**Comment by Eelviny** [comment]
Is this just a quick syntax fix or does this make the program function?

**Comment by feinstaub** [comment]
When I start the script without this fix, I get the above mentioned syntax error message.

Now I get 

```
  File "./nxt_filer", line 18, in <module>
    import gtk
```

because I have no python-gtk installed. So there might be a runtime error later.

**Comment by Eelviny** [comment]
As written in #85, this is because python-gtk is no longer supported.
I'm thinking that I'm going to reject this pull request as I may just remove the whole file.

**Comment by feinstaub** [comment]
Go ahead... (I will only cry a very small tear)

**Pull request closed without merging**
